# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fh0K6aAv3M5vvCNJsG3VwAOBvCe2wC2f
"""

cant_baldosas, cap_sensor = input().split(" ")
identif_baldosas = input().split()

cant_baldosas = int(cant_baldosas)
cap_sensor =int(cap_sensor)

for i in range(0,len(identif_baldosas),1):
    identif_baldosas[i] = int(identif_baldosas[i])
    
fallas_reales=0
fallas_sensor=0
contador =0
diccionario =dict()

for valor in identif_baldosas:
    if (valor in  diccionario):
        fallas_reales += 1 
    if ((valor in diccionario) and (contador-diccionario.get(valor)<= cap_sensor)):
        fallas_sensor += 1 
    diccionario[valor]= contador
    contador += 1
print (fallas_reales, fallas_sensor, cant_baldosas)